### ISSUE TITLE
URGENT: Use case and Partner Page Links on 3d.io broken

### ISSUE THREAD

**Issue by dburgauer** [archilogic-com/3dio-website#91]
"This site can't be reached" for:
- all showcases
- partner page

Issue seems to be that 3d.io is missing in URL: https://use-case/designer-portfolio-augmented-vr.html

**Comment by AVGP** [comment]
Looks like the deployment script somehow didn't resolve the links correctly, I'll take a look at it once I'm in the office (eta 15)

**Comment by AVGP** [comment]
Doesn't happen in a local build, so I'll try a rebuild on Travis and if that doesn't work, I'll deploy from my machine

**Comment by AVGP** [comment]
Fixed by simply re-running the release on Travis.

**Comment by dburgauer** [comment]
@AVGP Thanks!

**Comment by bnjm** [comment]
This seems to be still an issue with all the relative links at least on the index page, i.e. `href="use-cases.html"` (https://github.com/archilogic-com/3dio-website/blob/master/src/index.pug#L35) gets resolved to `https://use-cases.html`

@tomas-polach is this possibly related to the missing environment variables you came across yesterday? Like the following might be returning `''`: https://github.com/archilogic-com/3dio-website/blob/master/tasks/build.js#L23

**Comment by AVGP** [comment]
Travis should always set the TRAVIS_BRANCH variable accordingly.
Also, locally I don't have that variable but builds come out just fine (using relative URLs).

Anyway, for the time being I suggest to always run builds yourself locally and I disabled Travis until we're confident enough to run builds automatically again.

**Comment by AVGP** [comment]
@tomas-polach this is the bug we were talking about

**Comment by tomas-polach** [comment]
ok, fixed: it was a patch update in a dependency that changed file path generation resulting in double slashes inside file paths. to prevent this in the future i've added `url = path.join(x,y)` everywhere in build and deployment scripts (instead of the former `url = x+'/'+y`)
